"""Paper-defined constants and explicitly approved implementation constants."""

L_MAX = 15_000
OMEGA = (3_000, 5_000, 8_000, 10_000, 15_000)
PADDING_VALUE = 0
DIRECTION_VALUES = (-1, 1)

CLOSED_WORLD_CLASSES = 100
OPEN_WORLD_CLASSES = 101
UNMONITORED_CLASS_INDEX = 100

CANONICAL_SEED = 18
FIVE_TAB_SIZE = 5
MANIFEST_SCHEMA_VERSION = "msawf-manifest-v1"
SYNTHETIC_FIVE_TAB_PROTOCOL = "synthetic-five-tab-v1"
MULTILABEL_KSHOT_PROTOCOL = "multilabel-kshot-v1"
FIVE_SPLIT_PROTOCOL = "msawf-five-split-v1"
CANONICAL_CONSUMER_METHODS = ("MSAWF",)

STAGE_I_INSERTION_PROBABILITY = 0.2
STAGE_III_INSERTION_PROBABILITY = 0.2
NOISE_EVALUATION_PROBABILITIES = (0.0, 0.1, 0.2, 0.3)
